development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: divyaalias
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  reconnect: false
  database: myapp_prod
  pool: 5